<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cloud.docbyte.nuxeo</groupId>
    <artifactId>nuxeo-parent</artifactId>
    <version>2022.1.13-SNAPSHOT</version>
  </parent>

  <groupId>cloud.docbyte.nuxeo.web.ui</groupId>
  <artifactId>nuxeo-web-ui-parent</artifactId>
  <packaging>pom</packaging>
  <name>Nuxeo Web UI - Parent</name>
  <description>Nuxeo Web UI - Parent</description>
  <version>3.0.33-SNAPSHOT</version>

  <properties>
    <nuxeo.skip.enforcer>true</nuxeo.skip.enforcer>
    <nuxeo.target.version>2021.*</nuxeo.target.version>
    <nuxeo.platform.version>2022.1.13-SNAPSHOT</nuxeo.platform.version>
  </properties>

  <modules>
    <module>plugin/web-ui/addon</module>
    <module>plugin/web-ui/marketplace</module>
  </modules>

  <profiles>
    <profile>
      <id>ftest</id>
      <modules>
        <module>plugin/itests/addon</module>
        <module>plugin/itests/marketplace</module>
        <module>ftest/</module>
      </modules>
    </profile>
    <profile>
      <id>metrics</id>
      <modules>
        <module>plugin/metrics</module>
      </modules>
    </profile>
    <profile>
      <id>a11y</id>
      <modules>
        <module>plugin/a11y</module>
      </modules>
    </profile>
  </profiles>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-core</artifactId>
        <version>1.27.2</version>
      </dependency>

      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-api</artifactId>
        <version>1.27.2</version>
      </dependency>
      <dependency>

        <groupId>cloud.docbyte.nuxeo.web.ui</groupId>
        <artifactId>nuxeo-web-ui</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>cloud.docbyte.nuxeo.web.ui</groupId>
        <artifactId>nuxeo-web-ui-itests</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>cloud.docbyte.nuxeo.web.ui</groupId>
        <artifactId>nuxeo-web-ui-marketplace</artifactId>
        <version>${project.version}</version>
        <type>zip</type>
      </dependency>
      <dependency>
        <groupId>cloud.docbyte.nuxeo.web.ui</groupId>
        <artifactId>nuxeo-web-ui-marketplace-itests</artifactId>
        <version>${project.version}</version>
        <type>zip</type>
      </dependency>
    </dependencies>
  </dependencyManagement>


  <distributionManagement>
    <repository>
      <id>artifacts-snapshot-docbyte-com-docbyte-mvn-snapshot</id>
      <url>
        https://artifacts-beta-docbyte-com-518241560725.d.codeartifact.eu-west-1.amazonaws.com/maven/docbyte-mvn-beta/
      </url>
    </repository>
    <snapshotRepository>
      <id>artifacts-snapshot-docbyte-com-docbyte-mvn-snapshot</id>
      <url>
        https://artifacts-snapshot-docbyte-com-518241560725.d.codeartifact.eu-west-1.amazonaws.com/maven/docbyte-mvn-snapshot/
      </url>
    </snapshotRepository>
  </distributionManagement>



  <scm>
    <connection>scm:git:git://github.com/nuxeo/plugin-nuxeo-web-ui.git</connection>
    <developerConnection>scm:git:ssh://git@github.com:nuxeo/plugin-nuxeo-web-ui.git</developerConnection>
    <url>https://github.com/nuxeo/plugin-nuxeo-web-ui</url>
  </scm>

</project>
